---
title: "Phylogenetic Link System"
date: "`r Sys.Date()`"
output:   
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    toc_collapsed: true
---

[Return to Main](https://vandenbergrf.github.io/EthogramArchive/)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

.collapsible {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active, .collapsible:hover {
  background-color: #ccc;
}

/* Style the collapsible content. Note: hidden by default */
.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
  background-color: #f1f1f1;
}



# The Phylogenetic Tree

Below you will find a collection of links to the ethograms for the available phyla. 
To suggest an update, please specify which name changes (if any) and movements between different branches (if any) should be performed. Looking at you, bat phylogenists.
If your preferred genus/family/order/kingdom/etc. is not on this page yet, put in a request! For convenience, the branches will be built bottom-up.

## Link System


<button type="button" class="collapsible">Open Collapsible</button>
  <div class="content">
    <p>Lorem ipsum...</p>
  </div> 

